### ISSUE TITLE
[클린 아키텍쳐 연습] 이름을 가져오는 기능

### ISSUE THREAD

**Issue by laco-dev** [YAPP-Github/20th-ALL-Rounder-Team-2-iOS#20]
## 개요
- 클린 아키텍쳐 기반의 프로젝트에서 하나의 비즈니스 로직을 구현 해 보는 과정

## 요구사항
- 화면에 이름을 보여준다.
- UI 레이어는 구현하지 않는다 (ViewModel 까지만)
- 이름은 로컬 메모리에서 가져올 수 있으며 로컬에 데이터가 없는 경우 서버로부터 가져온다.
- 실제 디비나 서버를 구현하는게 아닌 가정 하에 결과 값을 반환한다.
```kotlin
internal class UserLocalDataSourceImpl: UserLocalDataSource {
    suspend fun getName(): Result<String?> {
      return Result.success(null)
   }
}

internal class UserRemoteDataSourceImpl: UserRemoteDataSource {
    suspend fun getName(): Result<String> {
      return Result.success("Android")
   }
}
...
```
- 뷰모델에서는 GetNameUseCase()를 사용해서 이름을 가져와야 한다.
- Hilt를 이용해 각 컴포넌트를 주입받도록 한다.

**Comment by yjyoon-dev** [comment]
## 질문
- 예시로 작성해주신 코드처럼 로컬에는 데이터가 항상 없고(null), 서버로부터 가져오는 것은 항상 성공한다는 가정하에 구현하면 될까요?
- 저번에 클린 아키텍쳐 모듈 추가할 때 app 모듈에 local 이랑 remote 의존성 추가하는걸 깜빡한 것 같은데, issue 열어서 마저 추가한 다음 브랜치 파서 진행할까요? ㅠ
